language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
install:
  - pip install -e . --use-mirrors
script: python setup.py test

matrix:
  include:
    python: 2.7
    install:
      - pip install pep8 --use-mirrors
    script: "pep8 --repeat --show-source --exclude=.venv,.tox,dist,doc,build,*.egg ."
